import styles from "./index.module.css";
import { type NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { api } from "@/utils/api";
import {Header} from "../components/Header"
import NavBar from "@/components/NavBar";
import { Box, Button, Flex, Text } from "@chakra-ui/react";
import { colors } from "./_app";

const Home: NextPage = () => {
  const data = null;
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  // @ts-ignore
  const { data: user } =  api.auth.create.useMutation(data);


  return (
    <>
      <Head>
        <title>cls</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box mx={5}  mb={5} >
      <Text size={'xxs'} textAlign={'center'}>get $30 off your first purchase <Text color={'lightblue'} display={'inline'}>Redeeme now!!</Text></Text>
        <NavBar/>
        <Box bg={'#FFF4EC99'} p={20}>
          <Text fontWeight={'bold'} textAlign={'center'} fontSize={'5xl'}>
          Become an Insider to earn <br/> $20 today!
          </Text>
          <Flex justifyContent={'center'}>
            <Button justifySelf={'center'} size={'lg'} bg={colors.dark} color={'white'}>Join now for free</Button>
          </Flex>
        </Box>
        <Box mt={5} bg={'#FFF4EC99'}>
        <Text p={5} textAlign={'center'} fontWeight={'bold'}>Insider Get</Text>
      </Box>
      </Box >


      
    </>
  );
};

export default Home;


